apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: health360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: shalmalee98/health360-reactapp:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 3001