apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: health360
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 31000